from datetime import datetime
from pathlib import Path
import json
import os
import sys
import atexit
import gc
from openai import OpenAI
from dotenv import load_dotenv

from quote_selector import select_quotes_for_agent
from get_semantic_tag import get_semantic_tag_weights

# Move log function here before first use
def log(msg: str) -> None:
    sys.stderr.write(str(msg) + "\n")

os.environ["TOKENIZERS_PARALLELISM"] = "false"

load_dotenv()
BASE_DIR = Path(__file__).parent.resolve()
OUTPUT_DIR = BASE_DIR / "agent_outputs"
SCENARIOS_DIR = BASE_DIR / "scenarios"
CORPUS_DIR = BASE_DIR / "care_ethics_corpus"
LATEST_RESULTS_PATH = BASE_DIR / "latest_results.json"
os.makedirs(OUTPUT_DIR, exist_ok=True)

LAST_QUERY_PATH = OUTPUT_DIR / ".last_query_care.txt"
LAST_RESPONSE_PATH = OUTPUT_DIR / ".last_response_care.txt"

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
if not os.getenv("OPENAI_API_KEY"):
    log("⚠️ OPENAI_API_KEY is not set; requests will fail.")
log(f"📁 BASE_DIR set to: {BASE_DIR}")
log(f"📂 OUTPUT_DIR: {OUTPUT_DIR}")
log(f"📂 SCENARIOS_DIR: {SCENARIOS_DIR}")

AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks

def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, primary_model
    except Exception as e:
        log(f"Primary model error: {e}")

    try:
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, fallback_model
    except Exception as e2:
        log(f"Fallback model error: {e2}")

    return "[No response generated by model]", fallback_model

def retrieve_care_ethics_quotes(query: str, scenario_id: str, limit_per_quote: int = 250):
    """
    Use quote selector to fetch top care ethics quotes instead of vectorstore.
    """
    school = "care_ethics_corpus"
    selected = select_quotes_for_agent(school, query, k_local=20)
    context = "\n".join(f"> {q['quote']}" for q in selected)
    top_quotes = [(q["quote"], None) for q in selected]
    return context, top_quotes

def respond_to_query(query: str, scenario_id: str, scenario_path=None, temperature: float = 0.7, max_tokens: int = 500, llm=None) -> str:
    if scenario_path is None:
        scenario_path = SCENARIOS_DIR / f"{scenario_id}.json"

    if not query or not scenario_id:
        raise ValueError("Both 'query' and 'scenario_id' must be provided.")

    # Use cache if same query
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            cached = LAST_RESPONSE_PATH.read_text().strip()
            if cached:
                log("⚡ Using cached Care Ethics response.")
                return cached

    # (Optional) get semantic tag weights
    try:
        tag_weights = get_semantic_tag_weights(scenario_id, scenario_dir=SCENARIOS_DIR, corpus_dir=CORPUS_DIR)
    except Exception:
        tag_weights = {}

    context, top_quotes = retrieve_care_ethics_quotes(query, scenario_id)

    prompt = f"""<s>[INST]
You are a care ethics assistant. Your role is to reason from care, prioritizing relationships, emotional resonance, and concrete human contexts.

- Your response should be grounded in the specifics of the scenario.
- Emphasize responsiveness, attentiveness, and moral sensitivity.
- Avoid rigid abstractions or purely outcome-based calculus.
- Use the following selected quotes for insight:

{context}

Ethical Question:
{query}

Care Ethics Answer:
[/INST]
"""

    messages = [
        {"role": "system", "content": "You are the Care Ethics member of the Ethical Parliament. Use relational, contextual reasoning and moral attention."},
        {"role": "user", "content": prompt},
    ]

    final_response, model_used = call_with_fallback(messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = OUTPUT_DIR / f"response_care_{timestamp}.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        for quote, _ in top_quotes:
            f.write(f"- {quote}\n")
        f.write("\nCare Ethics Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    if final_response.strip():
        LAST_RESPONSE_PATH.write_text(final_response.strip())

    gc.collect()
    return final_response

if __name__ == "__main__":
    scenario_files = sorted(SCENARIOS_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if scenario_files:
        sp = scenario_files[0]
        sid = sp.stem
        with open(sp, "r", encoding="utf-8") as f:
            data = json.load(f)
        q = data.get("ethical_question", "")
        print("Care Ethics Response:\n", respond_to_query(q, sid, scenario_path=sp))