import os
import gc
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

from pathlib import Path
from openai import OpenAI
from dotenv import load_dotenv

from quote_selector import select_quotes_for_agent
from get_semantic_tag import get_semantic_tag_weights

LAST_QUERY_PATH = Path("agent_outputs/.last_query_deont.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_deont.txt")

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

client = OpenAI(api_key=OPENAI_API_KEY)

def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks

def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, primary_model
    except Exception as e:
        print("Primary model error:", e)

    try:
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, fallback_model
    except Exception as e2:
        print("Fallback model error:", e2)

    return "[No response generated by model]", fallback_model

def retrieve_deontological_quotes(query: str, scenario_id: str, limit_per_quote: int = 250):
    """
    Replace the old vectorstore retrieval: use the quote selector to pick top deontological quotes.
    """
    school = "deontological_corpus"
    selected = select_quotes_for_agent(school, query, k_local=20)
    context = "\n".join(f"> {q['quote']}" for q in selected)
    top_quotes = [(q["quote"], None) for q in selected]
    return context, top_quotes

def respond_to_query(query: str, scenario_id: str, temperature: float = 0.4, max_tokens: int = 300, llm=None, scenario_path=None) -> str:
    if scenario_path is None:
        scenario_path = Path(f"scenarios/{scenario_id}.json")

    if not query or not scenario_id:
        raise ValueError("Both 'query' and 'scenario_id' must be provided.")

    # caching
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            print("⚡ Using cached deontological response.")
            return LAST_RESPONSE_PATH.read_text().strip()

    # Optionally load tag weights if your agent uses them
    try:
        tag_weights = get_semantic_tag_weights(scenario_id, scenario_dir=Path("scenarios"), corpus_dir=Path("deontological_corpus"))
    except Exception:
        tag_weights = {}

    context, top_quotes = retrieve_deontological_quotes(query, scenario_id)

    prompt = f"""<s>[INST]
You are a strict Kantian ethics assistant. Use the categorical imperative: reason via maxims you can will as universal laws. Do not appeal to outcomes or utilitarian trade-offs. Apply duties (truth, respect, autonomy, justice) clearly.

Here are selected deontological quotes for reference:
{context}

Ethical Question:
{query}

Deontological Answer:
[/INST]
"""

    messages = [
        {
            "role": "system",
            "content": (
                "You are the Deontological (Kantian) member of the Ethical Parliament. "
                "Always reason from duties, universalizability, and respect for persons as ends. "
                "Do not adopt consequentialist reasoning."
            )
        },
        {"role": "user", "content": prompt},
    ]

    final_response, model_used = call_with_fallback(
        messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens
    )
    print("🛰️ Deontology Agent used model:", model_used)

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_deont_{timestamp}.txt")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        for quote, _ in top_quotes:
            f.write(f"- {quote}\n")
        f.write("\nDeontological Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    gc.collect()
    return final_response

if __name__ == "__main__":
    import json
    from pathlib import Path as _P
    import glob
    scenario_files = sorted(_P("scenarios").glob("*.json"), key=os.path.getmtime, reverse=True)
    if scenario_files:
        sp = scenario_files[0]
        scenario_id = sp.stem
        with open(sp, "r", encoding="utf-8") as f:
            data = json.load(f)
        q = data.get("ethical_question", "")
        print("Deontological Response:\n", respond_to_query(q, scenario_id, scenario_path=sp))