import glob
from load_rawlsian_ethics_corpus import load_rawlsian_ethics_corpus
from langchain.schema import Document as LangchainDoc
import json
from pathlib import Path
from datetime import datetime
import os
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
import numpy as np
from get_semantic_tag import get_semantic_tag_weights
from openai import OpenAI
from dotenv import load_dotenv
import atexit
import gc

LAST_QUERY_PATH = Path("agent_outputs/.last_query_rawlsian.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_rawlsian.txt")

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
client = OpenAI(api_key=OPENAI_API_KEY)

FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

def _to_responses_input(messages):
    """Convert chat-completions style messages to Responses API input blocks."""
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks


def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    """
    Try primary (GPT-5 family) via Responses API if applicable; on empty/exception,
    fall back to chat.completions with fallback_model.
    Returns (text, model_used).
    """
    # 1) Try primary
    try:
        print(f"🛰️ Trying primary model: {primary_model}")
        if primary_model.startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (resp.output_text or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Primary model returned {len(text)} chars.")
            return text, primary_model
        else:
            print("⚠️ Primary model returned empty text; will try fallback…")
    except Exception as e:
        print(f"⚠️ Primary model error: {e}; will try fallback…")

    # 2) Fallback
    try:
        print(f"🛰️ Trying fallback model: {fallback_model}")
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Fallback model returned {len(text)} chars.")
            return text, fallback_model
        else:
            print("❌ Fallback model also returned empty text.")
            return "[No response generated by model]", fallback_model
    except Exception as e:
        print(f"❌ Fallback model error as well: {e}")
        return "[No response generated by model]", fallback_model

class Document:
    def __init__(self, content, metadata):
        self.content = content
        self.metadata = metadata or {}

def load_scenario_weights(scenario_id):
    print(f"🧠 Expanding tag weights with semantic overlap for scenario: {scenario_id}")
    return get_semantic_tag_weights(scenario_id, scenario_dir=Path("scenarios"), corpus_dir=Path("rawlsian_ethics_corpus"))

def normalize_tags(raw_tags):
    if isinstance(raw_tags, str):
        return [t.strip() for t in raw_tags.split(",")]
    elif isinstance(raw_tags, list):
        return [t.strip() for t in raw_tags]
    return []

def cosine_similarity(a, b):
    a = np.array(a).flatten()
    b = np.array(b).flatten()
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def retrieve_rawlsian_ethics_quotes(query: str, scenario_id: str, limit_per_quote: int = 250):
    from langchain_huggingface import HuggingFaceEmbeddings
    from load_rawlsian_ethics_corpus import load_rawlsian_ethics_corpus
    embedder = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    global vectorstore
    vectorstore = load_rawlsian_ethics_corpus()

    tag_weights = load_scenario_weights(scenario_id)
    print(f"🔧 Scenario Tag Weights: {tag_weights}")

    raw_docs = vectorstore.similarity_search(query, k=10)
    wrapped_docs = [Document(d.page_content, d.metadata) for d in raw_docs]

    def doc_score(doc):
        tags = normalize_tags(doc.metadata.get("tags", []))
        score = 0.0
        for tag in tags:
            tag_weight = tag_weights.get(tag, 0.0)
            if tag_weight > 0:
                print(f"🔍 Tag '{tag}' has semantic weight {tag_weight}")
            score += tag_weight
        print(f"🧪 Normalized Tags: {tags} → Score: {score:.2f}")
        return score

    doc_scores = {id(doc): doc_score(doc) for doc in wrapped_docs}

    quotes = []
    for doc in wrapped_docs:
        for line in doc.content.split("\n"):
            if line.strip().startswith(">"):
                quote = line.strip()[1:].strip()[:limit_per_quote]
                if quote:
                    quotes.append((quote, doc_scores[id(doc)]))

    if not quotes:
        del vectorstore
        del embedder
        import gc; gc.collect()
        return "", []

    quote_texts = [q[0] for q in quotes]
    quote_tag_scores = [q[1] for q in quotes]

    query_embedding = embedder.embed_query(query)
    quote_embeddings = embedder.embed_documents(quote_texts)

    ranked = []
    for i in range(len(quote_texts)):
        sim = cosine_similarity(query_embedding, quote_embeddings[i])
        sim = max(0.0, sim)
        tag_score = quote_tag_scores[i] if i < len(quote_tag_scores) else 0.0
        combined_score = tag_score * 2 + 0.2 * sim
        ranked.append((quote_texts[i], combined_score))

    ranked = sorted(ranked, key=lambda x: x[1], reverse=True)
    top_quotes = ranked[:3]

    for quote, score in top_quotes:
        print(f"📘 Quote Used (score: {score:.2f}): {quote}")

    # Cleanup to free memory
    del quote_embeddings
    del quote_texts
    del quote_tag_scores
    del query_embedding
    del wrapped_docs
    del raw_docs
    del doc_scores
    del ranked
    del vectorstore
    del embedder
    import gc; gc.collect()

    return "\n---\n".join([q for q, _ in top_quotes]), top_quotes

def respond_to_query(query: str, scenario_id: str, scenario_path=None, temperature: float = 0.7, max_tokens: int = 300, llm=None) -> str:
        # fallback if scenario_path not provided
    
    if scenario_path is None:
        scenario_path = Path(f"scenarios/{scenario_id}.json")
    
    if not query or not scenario_id:
        raise ValueError("Both 'query' and 'scenario_id' must be provided.")

    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            print("⚡ Skipping LLM call — using cached rawlsian ethics response.")
            return LAST_RESPONSE_PATH.read_text().strip()

    context, top_quotes = retrieve_rawlsian_ethics_quotes(query, scenario_id)

    # Build a clean, model-agnostic prompt (no [INST] wrappers)
    prompt = (
        "You are the Rawlsian member of the Ethical Parliament. Reason using justice as fairness: "
        "equal basic liberties, fair equality of opportunity, and the difference principle from behind the veil of ignorance. "
        "Be clear and rigorous.\n\n"
        "Guidelines:\n"
        "- Emphasize fairness and equal basic rights.\n"
        "- Evaluate decisions from the standpoint of the least advantaged.\n"
        "- Avoid utilitarian tradeoffs that violate individual liberties.\n"
        "- Where helpful, cite and weave in the corpus excerpts below.\n\n"
        f"Corpus excerpts (may be partial):\n{context}\n\n"
        f"Ethical Question:\n{query}\n\n"
        "Rawlsian Ethics Answer:\n"
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are the Rawlsian ethics agent in a multi-agent parliament. "
                "Reason from the original position behind a veil of ignorance; defend equal basic liberties, "
                "fair equality of opportunity, and permit inequalities only if they benefit the least advantaged."
            ),
        },
        {"role": "user", "content": prompt},
    ]

    # Debug: show outbound prompt preview
    try:
        preview = (prompt[:2000] + ("…" if len(prompt) > 2000 else ""))
        print("\n🔎 RAWLS outbound prompt preview:\n" + preview)
    except Exception:
        pass

    final_response, model_used = call_with_fallback(
        messages=messages,
        primary_model=AGENT_MODEL,
        fallback_model=FALLBACK_MODEL,
        max_tokens=max_tokens,
    )

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_{timestamp}.txt")

    with open(output_path, "w") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        f.write(f"Scenario ID: {scenario_id}\n")
        for quote, score in top_quotes:
            f.write(f"- {quote} (score: {score:.2f})\n")
        f.write("\nRawlsian Ethics Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    print(f"💾 Saved output to: {output_path}")
    return final_response

def cleanup_vectorstore():
    global vectorstore
    try:
        del vectorstore
    except NameError:
        pass
    gc.collect()

atexit.register(cleanup_vectorstore)

if __name__ == "__main__":
    scenario_files = sorted(Path("scenarios").glob("*.json"), key=os.path.getmtime, reverse=True)
    if not scenario_files:
        print("Error: No scenario files found in 'scenarios' directory.")
    else:
        scenario_path = scenario_files[0]
        scenario_id = scenario_path.stem
        with open(scenario_path) as sf:
            scenario_file = json.load(sf)
        query = scenario_file.get("ethical_question", "")
        if query:
            print("Rawlsian Ethics Response:\n" + respond_to_query(query, scenario_id, scenario_path=scenario_path))
        else:
            print(f"Error: 'ethical_question' not found in scenario file {scenario_path}")
