from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from load_utilitarian_corpus import load_utilitarian_corpus
from langchain.schema import Document as LangchainDoc
import json
from pathlib import Path
from datetime import datetime
import os
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
import numpy as np
from get_semantic_tag import get_semantic_tag_weights
from pathlib import Path
import gc
import atexit
import glob

from horizon_aggregator import (
    horizon_limited_aggregate,
    exponential_kernel,
    hyperbolic_kernel,
    estimate_horizon_from_tags,
)

from openai import OpenAI
from dotenv import load_dotenv


vectorstore = None
embedder = None

LAST_QUERY_PATH = Path("agent_outputs/.last_query_util.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_util.txt")


load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
client = OpenAI(api_key=OPENAI_API_KEY)

FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks

def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        print(f"🛰️ Trying primary model: {primary_model}")
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Primary model returned {len(text)} chars.")
            return text, primary_model
        else:
            print("⚠️ Primary model returned empty text; trying fallback…")
    except Exception as e:
        print(f"⚠️ Primary model error: {e}; trying fallback…")

    try:
        print(f"🛰️ Trying fallback model: {fallback_model}")
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Fallback model returned {len(text)} chars.")
            return text, fallback_model
        else:
            print("❌ Fallback model also returned empty text.")
            return "[No response generated by model]", fallback_model
    except Exception as e2:
        print(f"❌ Fallback model error: {e2}")
        return "[No response generated by model]", fallback_model


class Document:
    def __init__(self, content, metadata):
        self.content = content
        self.metadata = metadata or {}

def load_scenario_weights(scenario_id):
    print(f"🧠 Expanding tag weights with semantic overlap for scenario: {scenario_id}")
    return get_semantic_tag_weights(scenario_id, scenario_dir=Path("scenarios"), corpus_dir=Path("utilitarian_corpus"))

def normalize_tags(raw_tags):
    if isinstance(raw_tags, str):
        return [t.strip() for t in raw_tags.split(",")]
    elif isinstance(raw_tags, list):
        return [t.strip() for t in raw_tags]
    return []

def cosine_similarity(a, b):
    a = np.array(a).flatten()
    b = np.array(b).flatten()
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def retrieve_utilitarian_quotes(query: str, scenario_id: str, limit_per_quote: int = 250):
    from langchain_chroma import Chroma
    from langchain_huggingface import HuggingFaceEmbeddings
    from load_utilitarian_corpus import load_utilitarian_corpus

    global vectorstore, embedder
    embedder = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    vectorstore = load_utilitarian_corpus()

    tag_weights = load_scenario_weights(scenario_id)
    print(f"\U0001f527 Scenario Tag Weights: {tag_weights}")

    raw_docs = vectorstore.similarity_search(query, k=10)
    print(f"🔍 Retrieved {len(raw_docs)} documents for similarity search.")
    wrapped_docs = [Document(d.page_content, d.metadata) for d in raw_docs]
    if wrapped_docs:
        print("🔍 Sample document content snippet:", wrapped_docs[0].content[:100])

    def doc_score(doc):
        tags = normalize_tags(doc.metadata.get("tags", []))
        score = 0.0
        for tag in tags:
            tag_weight = tag_weights.get(tag, 0.0)
            if tag_weight > 0:
                print(f"\U0001f50d Tag '{tag}' has semantic weight {tag_weight}")
            score += tag_weight
        print(f"\U0001f9ea Normalized Tags: {tags} → Score: {score:.2f}")
        return score

    doc_scores = {id(doc): doc_score(doc) for doc in wrapped_docs}

    quotes = []
    for doc in wrapped_docs:
        for line in doc.content.split("\n"):
            if line.strip().startswith(">"):
                quote = line.strip()[1:].strip()[:limit_per_quote]
                if quote:
                    quotes.append((quote, doc_scores[id(doc)]))

    if not quotes:
        print("⚠️ No '>'-prefixed quotes found, using document excerpts as fallback quotes.")
        for doc in wrapped_docs[:3]:
            lines = [l for l in doc.content.split("\n") if l.strip()]
            excerpt = lines[0].strip()[:limit_per_quote] if lines else ""
            if excerpt:
                quotes.append((excerpt, doc_scores[id(doc)]))
    if not quotes:
        return "", []

    quote_texts = [q[0] for q in quotes]
    quote_tag_scores = [q[1] for q in quotes]

    query_embedding = embedder.embed_query(query)
    quote_embeddings = embedder.embed_documents(quote_texts)

    ranked = []
    for i in range(len(quote_texts)):
        sim = cosine_similarity(query_embedding, quote_embeddings[i])
        sim = max(0.0, sim)
        tag_score = quote_tag_scores[i] if i < len(quote_tag_scores) else 0.0
        combined_score = tag_score * 2 + 0.2 * sim
        ranked.append((quote_texts[i], combined_score))

    ranked = sorted(ranked, key=lambda x: x[1], reverse=True)
    top_quotes = ranked[:3]

    for quote, score in top_quotes:
        print(f"\U0001f4d8 Quote Used (score: {score:.2f}): {quote}")

    return "\n---\n".join([q for q, _ in top_quotes]), top_quotes


# ---------------------------------------------------------------------- #
#  Horizon‑limited utility helper                                        #
# ---------------------------------------------------------------------- #
def _compute_horizon_limited_summary(scenario_tags: list[str],
                                     values: list[float],
                                     distances: list[float]) -> str:
    """
    Given the scenario's temporal tags plus parallel lists of `values`
    and their temporal `distances` (same metric everywhere!), return a
    short natural‑language summary for the LLM prompt.  We use a
    hyperbolic kernel by default.
    """
    H = estimate_horizon_from_tags([t.lower() for t in scenario_tags])
    agg = horizon_limited_aggregate(
        values,
        distances,
        horizon=H,
        kernel=hyperbolic_kernel(scale=0.05),
    )
    return (
        f"Horizon‑limited aggregation (H = {H:.0f} units, hyperbolic scale 0.05) "
        f"yields a net utility of {agg:.2f} for the in‑horizon outcomes."
    )


def respond_to_query(query: str, scenario_id: str, temperature: float = 0.5, max_tokens: int = 300, llm=None, scenario_path=None) -> str:
   
    if scenario_path is None:
        scenario_path = Path(f"scenarios/{scenario_id}.json")
    
    if not query or not scenario_id:
        raise ValueError("Both 'query' and 'scenario_id' must be provided.")

    # Skip LLM if query hasn't changed
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            print("⚡ Skipping LLM call — using cached utilitarian response.")
            return LAST_RESPONSE_PATH.read_text().strip()

    with open(scenario_path, "r") as f:
        scenario_file = json.load(f)

    # Attempt to build a horizon‑limited summary if the scenario JSON
    # provides `temporal_tags`, `outcome_values`, and `outcome_distances`.
    horizon_summary = ""
    if isinstance(scenario_file, dict):
        tags  = scenario_file.get("temporal_tags", [])
        vals  = scenario_file.get("outcome_values", [])
        dists = scenario_file.get("outcome_distances", [])
        if tags and vals and dists and len(vals) == len(dists):
            try:
                horizon_summary = _compute_horizon_limited_summary(tags, vals, dists)
                print("🪐 Horizon summary added to prompt.")
            except Exception as e:
                print(f"⚠️ Horizon summary skipped: {e}")

    context, top_quotes = retrieve_utilitarian_quotes(query, scenario_id)

    import time; time.sleep(2)

    prompt = f"""
<s>[INST] You are a utilitarian ethics assistant. Your goal is to determine the action best aligned with utilitarian principles, using the corpus excerpts provided.

- Base your decision entirely on consequences.
- Do not assume harm is always wrong—utilitarianism may permit harm if it maximizes net well-being.
- Ignore proximity and immediacy unless they affect outcomes.
- Use the following corpus excerpts in your reasoning. Explicitly reference or paraphrase their logic where applicable.

Corpus Materials:
{context}

{horizon_summary}

Ethical Question:
{query}

Utilitarian Answer:
[/INST]
"""

    messages = [
        {"role": "system", "content": "You are the Utilitarian member of the Ethical Parliament. Base recommendations on maximizing aggregate well‑being (rule‑utilitarian when relevant), and reference the provided corpus context succinctly."},
        {"role": "user", "content": prompt},
    ]
    final_response, model_used = call_with_fallback(messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens)

    import time; time.sleep(1)

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_{timestamp}.txt")

    with open(output_path, "w") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        f.write(f"Scenario ID: {scenario_id}\n")
        for quote, score in top_quotes:
            f.write(f"- {quote} (score: {score:.2f})\n")
        f.write("\nUtilitarian Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    print(f"💾 Saved output to: {output_path}")
    return final_response

def cleanup_vectorstore():
    global vectorstore, embedder
    vectorstore = None
    embedder = None
    gc.collect()

atexit.register(cleanup_vectorstore)

if __name__ == "__main__":
    scenario_files = sorted(Path("scenarios").glob("*.json"), key=os.path.getmtime, reverse=True)
    if not scenario_files:
        raise FileNotFoundError("No scenario files found in 'scenarios' directory.")
    latest_scenario_path = scenario_files[0]
    scenario_id = latest_scenario_path.stem
    with open(latest_scenario_path, "r") as f:
        scenario_file = json.load(f)
    query = scenario_file["ethical_question"]
    print("Utilitarian Response:\n" + respond_to_query(query, scenario_id))
