from pathlib import Path
import os
import json
import gc
from datetime import datetime

from dotenv import load_dotenv
from openai import OpenAI

from quote_selector import select_quotes_for_agent

LAST_QUERY_PATH = Path("agent_outputs/.last_query_util.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_util.txt")

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

client = OpenAI(api_key=OPENAI_API_KEY)


def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks


def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, primary_model
    except Exception as e:
        print("Primary model error:", e)

    try:
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, fallback_model
    except Exception as e2:
        print("Fallback model error:", e2)

    return "[No response generated by model]", fallback_model


def respond_to_query(query: str, scenario_id: str, temperature: float = 0.5, max_tokens: int = 300, llm=None, scenario_path=None) -> str:
    if scenario_path is None:
        scenario_path = Path(f"scenarios/{scenario_id}.json")

    if not query or not scenario_id:
        raise ValueError("Both 'query' and 'scenario_id' must be provided.")

    # Use cached result if same query
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            print("⚡ Using cached utilitarian response.")
            return LAST_RESPONSE_PATH.read_text().strip()

    # Load scenario JSON if needed
    if scenario_path.exists():
        with open(scenario_path, "r", encoding="utf-8") as f:
            scenario_json = json.load(f)
    else:
        scenario_json = {}

    # Get quotes via selector
    school = "utilitarian_corpus"
    selected = select_quotes_for_agent(school, query, k_local=20)
    context = "\n".join(f"> {q['quote']}" for q in selected)
    top_quotes = [(q["quote"], None) for q in selected]

    prompt = f"""<s>[INST] You are a utilitarian ethics assistant. Your goal is to determine the action best aligned with utilitarian principles, given the scenario and relevant quotes below.

Selected quotes:
{context}

Ethical Question:
{query}

Utilitarian Answer:
[/INST]
"""

    messages = [
        {"role": "system", "content": "You are the Utilitarian member of the Ethical Parliament. Base your answer on aggregate well-being and consequences, referencing the provided quotes where helpful."},
        {"role": "user", "content": prompt},
    ]

    final_response, model_used = call_with_fallback(messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens)

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_util_{timestamp}.txt")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        for quote, _ in top_quotes:
            f.write(f"- {quote}\n")
        f.write("\nUtilitarian Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    gc.collect()
    return final_response


if __name__ == "__main__":
    import glob
    scenario_files = sorted(Path("scenarios").glob("*.json"), key=os.path.getmtime, reverse=True)
    if scenario_files:
        sp = scenario_files[0]
        scenario_id = sp.stem
        with open(sp, "r", encoding="utf-8") as f:
            data = json.load(f)
        query = data.get("ethical_question", "")
        print("Utilitarian Response:\n", respond_to_query(query, scenario_id, scenario_path=sp))