MODEL_PATH = "../mistral-7b-instruct-v0.2.Q4_K_M.gguf"
from langchain_chroma import Chroma
from generic_loader import load_corpus
from sklearn.metrics.pairwise import cosine_similarity
import json
from pathlib import Path
LAST_QUERY_PATH = Path("agent_outputs/.last_query_virtue.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_virtue.txt")
import glob
from datetime import datetime
import os
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
import gc
import numpy as np
from get_semantic_tag import get_semantic_tag_weights
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

# Use OpenAI mini for agent steps (overridable)
AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
client = OpenAI(api_key=OPENAI_API_KEY)

FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks

def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        print(f"🛰️ Trying primary model: {primary_model}")
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Primary model returned {len(text)} chars.")
            return text, primary_model
        else:
            print("⚠️ Primary model returned empty text; trying fallback…")
    except Exception as e:
        print(f"⚠️ Primary model error: {e}; trying fallback…")

    try:
        print(f"🛰️ Trying fallback model: {fallback_model}")
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            print(f"✅ Fallback model returned {len(text)} chars.")
            return text, fallback_model
        else:
            print("❌ Fallback model also returned empty text.")
            return "[No response generated by model]", fallback_model
    except Exception as e2:
        print(f"❌ Fallback model error: {e2}")
        return "[No response generated by model]", fallback_model

import atexit

def cleanup_vectorstore():
    global vectorstore
    global embedder
    try:
        del vectorstore
    except NameError:
        pass
    try:
        del embedder
    except NameError:
        pass
    gc.collect()

atexit.register(cleanup_vectorstore)

def _make_embedder():
    provider = os.getenv("EP_EMBEDDINGS", "openai").lower()
    if provider == "openai":
        from langchain_openai import OpenAIEmbeddings
        model = os.getenv("EP_EMBED_MODEL", "text-embedding-3-small")
        return OpenAIEmbeddings(model=model)
    else:
        # Falls back to HuggingFace locally if requested
        from langchain_huggingface import HuggingFaceEmbeddings
        model = os.getenv("EP_HF_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
        return HuggingFaceEmbeddings(model_name=model)

class Document:
    def __init__(self, content, metadata):
        self.content = content
        self.metadata = metadata or {}

def load_scenario_weights(scenario_id):
    print(f"🧠 Expanding tag weights with semantic overlap for scenario: {scenario_id}")
    return get_semantic_tag_weights(scenario_id, scenario_dir=Path("scenarios"), corpus_dir=Path("virtue_ethics_corpus"))


def normalize_tags(raw_tags):
    if isinstance(raw_tags, str):
        return [t.strip() for t in raw_tags.split(",")]
    elif isinstance(raw_tags, list):
        return [t.strip() for t in raw_tags]
    return []

def cosine_similarity(a, b):
    a = np.array(a).flatten()
    b = np.array(b).flatten()
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def retrieve_virtue_ethics_quotes(query: str, scenario_id: str, limit_per_quote: int = 250):
    tag_weights = load_scenario_weights(scenario_id)
    print(f"🔧 Scenario Tag Weights: {tag_weights}")

    raw_docs = vectorstore.similarity_search(query, k=10)
    wrapped_docs = [Document(d.page_content, d.metadata) for d in raw_docs]

    def doc_score(doc):
        tags = normalize_tags(doc.metadata.get("tags", []))
        score = 0.0
        for tag in tags:
            tag_weight = tag_weights.get(tag, 0.0)
            if tag_weight > 0:
                print(f"🔍 Tag '{tag}' has semantic weight {tag_weight}")
            score += tag_weight
        print(f"🧪 Normalized Tags: {tags} → Score: {score:.2f}")
        return score

    doc_scores = {id(doc): doc_score(doc) for doc in wrapped_docs}

    quotes = []
    for doc in wrapped_docs:
        for line in doc.content.split("\n"):
            if line.strip().startswith(">"):
                quote = line.strip()[1:].strip()[:limit_per_quote]
                if quote:
                    quotes.append((quote, doc_scores[id(doc)]))

    if not quotes:
        return "", []

    quote_texts = [q[0] for q in quotes]
    quote_tag_scores = [q[1] for q in quotes]

    query_embedding = embedder.embed_query(query)
    quote_embeddings = embedder.embed_documents(quote_texts)

    ranked = []
    for i in range(len(quote_texts)):
        sim = cosine_similarity(query_embedding, quote_embeddings[i])
        sim = max(0.0, sim)
        tag_score = quote_tag_scores[i] if i < len(quote_tag_scores) else 0.0
        combined_score = tag_score * 2 + 0.2 * sim
        ranked.append((quote_texts[i], combined_score))

    ranked = sorted(ranked, key=lambda x: x[1], reverse=True)
    top_quotes = ranked[:3]

    for quote, score in top_quotes:
        print(f"📘 Quote Used (score: {score:.2f}): {quote}")

    del tag_weights
    del raw_docs
    del wrapped_docs
    del quote_embeddings
    del quote_texts
    del quote_tag_scores
    del ranked
    gc.collect()

    return "\n---\n".join([q for q, _ in top_quotes]), top_quotes

def respond_to_query(query=None, scenario_id=None, scenario_path=None, temperature: float = 0.7, max_tokens: int = 300, llm=None) -> str:
    # Load vectorstore and embedder only when needed
    global embedder
    global vectorstore
    embedder = _make_embedder()
    # Persisted, Render-friendly collection; dir name == collection name
    vectorstore = load_corpus("virtue_ethics_corpus", "virtue_ethics_corpus")

    if scenario_path:
        try:
            with open(scenario_path, "r") as f:
                scenario_data = json.load(f)
                query = scenario_data.get("ethical_question", query)
                scenario_id = Path(scenario_path).stem
        except FileNotFoundError:
            print(f"❌ Provided scenario file not found: {scenario_path}")
            return "[ERROR] Scenario file not found."

    if query is None or scenario_id is None:
        print("⚠️ No query or scenario ID provided to respond_to_query. Aborting.")
        return "[ERROR] Missing input."
    # Skip LLM if query hasn't changed
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            print("⚡ Skipping LLM call — using cached virtue ethics response.")
            return LAST_RESPONSE_PATH.read_text().strip()
    context, top_quotes = retrieve_virtue_ethics_quotes(query, scenario_id)

    # Cleanup RAG components
    del embedder
    del vectorstore
    gc.collect()

    prompt = f"""<s>[INST] You are a virtue ethics assistant. Your task is to generate a detailed answer from the perspective of virtue ethics to the ethical scenario provided below. You should reason from the perspective of virtue ethics, focusing on character, habituation, and human flourishing.
    - Prioritize the development of moral character and virtues over rule-based moral frameworks.
    - Use moral exemplars, narrative analogies, and lived experience as sources of ethical insight.
    - Provide a specific course of action consistent with one path a virtue ethicists could recommend.

    Here are the corpus materials for reference:
    {context}
    Ethical Question:
    {query}
    [/INST]
    """

    messages = [
        {"role": "system", "content": "You are the Virtue Ethics member of the Ethical Parliament. Reason from virtue ethics: character, habituation, practical wisdom, and human flourishing. Be concrete; use exemplars when helpful."},
        {"role": "user", "content": prompt},
    ]
    final_response, model_used = call_with_fallback(messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens)

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_virtue_{timestamp}.txt")

    with open(output_path, "w") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        f.write(f"Scenario ID: {scenario_id}\n")
        for quote, score in top_quotes:
            f.write(f"- {quote} (score: {score:.2f})\n")
        f.write("\nVirtue Ethics Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    print(f"💾 Saved output to: {output_path}")

    # Save cache for last query/response
    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    del context
    del top_quotes
    gc.collect()

    return final_response


if __name__ == "__main__":
    # Auto-detect the most recent scenario file
    scenario_files = sorted(glob.glob("scenarios/*.json"), key=os.path.getmtime, reverse=True)
    if scenario_files:
        scenario_path = scenario_files[0]
        scenario_id = Path(scenario_path).stem
        try:
            with open(scenario_path) as f:
                scenario_file = json.load(f)
                query = scenario_file.get("ethical_question", "")
                if query:
                    print("Virtue Ethics Response:\n" + respond_to_query(query=query, scenario_id=scenario_id, scenario_path=scenario_path))
                else:
                    print("⚠️ No ethical question found in the scenario file.")
        except FileNotFoundError:
            print(f"❌ Scenario file not found: {scenario_path}")
    else:
        print("❌ No scenario files found in 'scenarios/'")
