import json
from pathlib import Path
import os
import gc
from datetime import datetime

from dotenv import load_dotenv
from openai import OpenAI

from quote_selector import select_quotes_for_agent

LAST_QUERY_PATH = Path("agent_outputs/.last_query_virtue.txt")
LAST_RESPONSE_PATH = Path("agent_outputs/.last_response_virtue.txt")

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise EnvironmentError("OPENAI_API_KEY environment variable not set.")

# Use OpenAI for agent steps (override model via env)
AGENT_MODEL = os.getenv("OPENAI_AGENT_MODEL", "gpt-5-mini")
FALLBACK_MODEL = os.getenv("OPENAI_AGENT_FALLBACK_MODEL", "gpt-4o-mini")

client = OpenAI(api_key=OPENAI_API_KEY)

def _to_responses_input(messages):
    blocks = []
    for m in messages:
        role = m.get("role", "user")
        text = m.get("content", "")
        blocks.append({
            "role": role,
            "content": [{"type": "text", "text": text}]
        })
    return blocks

def call_with_fallback(messages, primary_model: str, fallback_model: str, max_tokens: int):
    try:
        if primary_model.lower().startswith("gpt-5"):
            resp = client.responses.create(
                model=primary_model,
                input=_to_responses_input(messages),
                max_output_tokens=max_tokens,
            )
            text = (getattr(resp, "output_text", "") or "").strip()
        else:
            resp = client.chat.completions.create(
                model=primary_model,
                messages=messages,
                max_completion_tokens=max_tokens,
            )
            text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, primary_model
    except Exception as e:
        print("Primary model error:", e)
    # fallback
    try:
        resp = client.chat.completions.create(
            model=fallback_model,
            messages=messages,
            max_completion_tokens=max_tokens,
        )
        text = (resp.choices[0].message.content or "").strip()
        if text:
            return text, fallback_model
    except Exception as e2:
        print("Fallback model error:", e2)
    return "[No response generated by model]", fallback_model

def respond_to_query(query=None, scenario_id=None, scenario_path=None, temperature: float = 0.7, max_tokens: int = 300, llm=None):
    # Load scenario from file if provided
    if scenario_path:
        try:
            with open(scenario_path, "r") as f:
                scenario_data = json.load(f)
                query = scenario_data.get("ethical_question", query)
                scenario_id = Path(scenario_path).stem
        except FileNotFoundError:
            return "[ERROR] Scenario file not found."

    if query is None or scenario_id is None:
        return "[ERROR] Missing input."

    # Cache reuse
    if LAST_QUERY_PATH.exists() and LAST_RESPONSE_PATH.exists():
        last_query = LAST_QUERY_PATH.read_text().strip()
        if query.strip() == last_query:
            return LAST_RESPONSE_PATH.read_text().strip()

    # Use quote selector instead of vector/RAG
    school = "virtue_ethics_corpus"
    selected = select_quotes_for_agent(school, query, k_local=20)
    context = "\n".join(f"> {q['quote']}" for q in selected)
    top_quotes = [(q["quote"], None) for q in selected]

    prompt = f"""<s>[INST] You are a virtue ethics assistant. Your task is to generate a detailed answer from the perspective of virtue ethics to the ethical scenario provided below. You should reason from the perspective of virtue ethics, focusing on character, habituation, and human flourishing.
- Prioritize the development of moral character and virtues over rule-based moral frameworks.
- Use moral exemplars, narrative analogies, and lived experience as sources of ethical insight.
- Provide a specific course of action consistent with one path a virtue ethicist could recommend.
- Keep your resposne to no less than five and no more than seven paragraphs 
- Use the following quotes and checklist for formulating your response
    Virtue Ethics Content Checklist
	    1.	Name the key virtues and vices in tension
            Example: courage vs. recklessness; justice vs. favoritism.
	    2.	Describe concrete habits (hexeis) to practice this week
            These habits should cultivate the relevant virtues through repeated, observable actions.
	    3.	Offer one moral exemplar (historical or local)
            Explain what that exemplar would do in this specific scenario and why.
	    4.	Anticipate tradeoffs and risks
            Show how to remain virtuous under pressure or uncertainty.
	    5.	List likely failure modes and how to course-correct without cynicism
            Identify pitfalls and describe ways to recover moral direction constructively.
	    6.	Give one measurable signal of progress for each action-plan step
            Each signal should indicate whether virtue is being developed or maintained.


Here are the selected quotes for reference:
{context}

Ethical Question:
{query}
[/INST]
"""

    messages = [
        {"role": "system", "content": "You are the Virtue Ethics member of the Ethical Parliament. Reason from virtue ethics: character, habituation, practical wisdom, flourishing. Use examples when helpful."},
        {"role": "user", "content": prompt},
    ]
    final_response, model_used = call_with_fallback(messages, AGENT_MODEL, FALLBACK_MODEL, max_tokens=max_tokens)

    os.makedirs("agent_outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = Path(f"agent_outputs/response_virtue_{timestamp}.txt")
    with open(output_path, "w") as f:
        f.write(f"Ethical Question: {query}\n\n")
        f.write("Top Quotes Used:\n")
        for quote, _ in top_quotes:
            f.write(f"- {quote}\n")
        f.write("\nVirtue Ethics Response:\n")
        f.write(final_response + "\n")
        f.write(f"\n(Model used: {model_used})\n")

    LAST_QUERY_PATH.write_text(query.strip())
    LAST_RESPONSE_PATH.write_text(final_response.strip())

    gc.collect()
    return final_response

if __name__ == "__main__":
    # Optional: run with the latest scenario
    import glob
    scenario_files = sorted(glob.glob("scenarios/*.json"), key=os.path.getmtime, reverse=True)
    if scenario_files:
        sp = scenario_files[0]
        scen_id = Path(sp).stem
        with open(sp) as f:
            data = json.load(f)
        q = data.get("ethical_question", "")
        print("Virtue Ethics Response:\n", respond_to_query(query=q, scenario_id=scen_id, scenario_path=sp))